// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: orchestrator.proto

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckpointSnapshotState int32

const (
	CheckpointSnapshotState_CHECKPOINT_SNAPSHOT_UNKNOWN            CheckpointSnapshotState = 0
	CheckpointSnapshotState_CHECKPOINT_SNAPSHOT_IN_PROGRESS        CheckpointSnapshotState = 1
	CheckpointSnapshotState_CHECKPOINT_SNAPSHOT_COMMITTED          CheckpointSnapshotState = 2
	CheckpointSnapshotState_CHECKPOINT_SNAPSHOT_NOT_COMMITTED      CheckpointSnapshotState = 3
	CheckpointSnapshotState_CHECKPOINT_SNAPSHOT_DURABILITY_UNKNOWN CheckpointSnapshotState = 4
	// A successful RAM capture is retained for explicit local recovery. It is
	// not yet a committed snapshot, and must not be marked failed by timeout.
	CheckpointSnapshotState_CHECKPOINT_SNAPSHOT_CAPTURED CheckpointSnapshotState = 5
)

// Enum value maps for CheckpointSnapshotState.
var (
	CheckpointSnapshotState_name = map[int32]string{
		0: "CHECKPOINT_SNAPSHOT_UNKNOWN",
		1: "CHECKPOINT_SNAPSHOT_IN_PROGRESS",
		2: "CHECKPOINT_SNAPSHOT_COMMITTED",
		3: "CHECKPOINT_SNAPSHOT_NOT_COMMITTED",
		4: "CHECKPOINT_SNAPSHOT_DURABILITY_UNKNOWN",
		5: "CHECKPOINT_SNAPSHOT_CAPTURED",
	}
	CheckpointSnapshotState_value = map[string]int32{
		"CHECKPOINT_SNAPSHOT_UNKNOWN":            0,
		"CHECKPOINT_SNAPSHOT_IN_PROGRESS":        1,
		"CHECKPOINT_SNAPSHOT_COMMITTED":          2,
		"CHECKPOINT_SNAPSHOT_NOT_COMMITTED":      3,
		"CHECKPOINT_SNAPSHOT_DURABILITY_UNKNOWN": 4,
		"CHECKPOINT_SNAPSHOT_CAPTURED":           5,
	}
)

func (x CheckpointSnapshotState) Enum() *CheckpointSnapshotState {
	p := new(CheckpointSnapshotState)
	*p = x
	return p
}

func (x CheckpointSnapshotState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointSnapshotState) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestrator_proto_enumTypes[0].Descriptor()
}

func (CheckpointSnapshotState) Type() protoreflect.EnumType {
	return &file_orchestrator_proto_enumTypes[0]
}

func (x CheckpointSnapshotState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointSnapshotState.Descriptor instead.
func (CheckpointSnapshotState) EnumDescriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

type CheckpointRuntimeState int32

const (
	CheckpointRuntimeState_CHECKPOINT_RUNTIME_UNKNOWN       CheckpointRuntimeState = 0
	CheckpointRuntimeState_CHECKPOINT_RUNTIME_TRANSITIONING CheckpointRuntimeState = 1
	CheckpointRuntimeState_CHECKPOINT_RUNTIME_RUNNING       CheckpointRuntimeState = 2
	CheckpointRuntimeState_CHECKPOINT_RUNTIME_STOPPED       CheckpointRuntimeState = 3
)

// Enum value maps for CheckpointRuntimeState.
var (
	CheckpointRuntimeState_name = map[int32]string{
		0: "CHECKPOINT_RUNTIME_UNKNOWN",
		1: "CHECKPOINT_RUNTIME_TRANSITIONING",
		2: "CHECKPOINT_RUNTIME_RUNNING",
		3: "CHECKPOINT_RUNTIME_STOPPED",
	}
	CheckpointRuntimeState_value = map[string]int32{
		"CHECKPOINT_RUNTIME_UNKNOWN":       0,
		"CHECKPOINT_RUNTIME_TRANSITIONING": 1,
		"CHECKPOINT_RUNTIME_RUNNING":       2,
		"CHECKPOINT_RUNTIME_STOPPED":       3,
	}
)

func (x CheckpointRuntimeState) Enum() *CheckpointRuntimeState {
	p := new(CheckpointRuntimeState)
	*p = x
	return p
}

func (x CheckpointRuntimeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointRuntimeState) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestrator_proto_enumTypes[1].Descriptor()
}

func (CheckpointRuntimeState) Type() protoreflect.EnumType {
	return &file_orchestrator_proto_enumTypes[1]
}

func (x CheckpointRuntimeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointRuntimeState.Descriptor instead.
func (CheckpointRuntimeState) EnumDescriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

type SandboxConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data required for creating a new sandbox.
	TemplateId         string            `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	BuildId            string            `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	KernelVersion      string            `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	FirecrackerVersion string            `protobuf:"bytes,4,opt,name=firecracker_version,json=firecrackerVersion,proto3" json:"firecracker_version,omitempty"`
	HugePages          bool              `protobuf:"varint,5,opt,name=huge_pages,json=hugePages,proto3" json:"huge_pages,omitempty"`
	SandboxId          string            `protobuf:"bytes,6,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	EnvVars            map[string]string `protobuf:"bytes,7,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Metadata about the sandbox.
	Metadata    map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Alias       *string           `protobuf:"bytes,9,opt,name=alias,proto3,oneof" json:"alias,omitempty"`
	EnvdVersion string            `protobuf:"bytes,10,opt,name=envd_version,json=envdVersion,proto3" json:"envd_version,omitempty"`
	Vcpu        int64             `protobuf:"varint,11,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	RamMb       int64             `protobuf:"varint,12,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`
	TeamId      string            `protobuf:"bytes,13,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// Maximum length of the sandbox in Hours.
	MaxSandboxLength int64   `protobuf:"varint,14,opt,name=max_sandbox_length,json=maxSandboxLength,proto3" json:"max_sandbox_length,omitempty"`
	TotalDiskSizeMb  int64   `protobuf:"varint,15,opt,name=total_disk_size_mb,json=totalDiskSizeMb,proto3" json:"total_disk_size_mb,omitempty"`
	Snapshot         bool    `protobuf:"varint,16,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	BaseTemplateId   string  `protobuf:"bytes,17,opt,name=base_template_id,json=baseTemplateId,proto3" json:"base_template_id,omitempty"`
	AutoPause        bool    `protobuf:"varint,18,opt,name=auto_pause,json=autoPause,proto3" json:"auto_pause,omitempty"`
	EnvdAccessToken  *string `protobuf:"bytes,19,opt,name=envd_access_token,json=envdAccessToken,proto3,oneof" json:"envd_access_token,omitempty"`
	ExecutionId      string  `protobuf:"bytes,20,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// Whether the sandbox should have access to the internet.
	// This is optional only for backwards compatibility.
	// After migration, the optional keyword can be removed.
	AllowInternetAccess *bool                 `protobuf:"varint,21,opt,name=allow_internet_access,json=allowInternetAccess,proto3,oneof" json:"allow_internet_access,omitempty"`
	Network             *SandboxNetworkConfig `protobuf:"bytes,22,opt,name=network,proto3,oneof" json:"network,omitempty"`
	VolumeMounts        []*SandboxVolumeMount `protobuf:"bytes,23,rep,name=volumeMounts,proto3" json:"volumeMounts,omitempty"`
	// Auto-resume policy for paused sandboxes.
	AutoResume *SandboxAutoResumeConfig `protobuf:"bytes,24,opt,name=auto_resume,json=autoResume,proto3,oneof" json:"auto_resume,omitempty"`
	// When true, a timeout auto-pause takes a filesystem-only snapshot (no
	// memory) instead of a full memory snapshot. Only meaningful when auto_pause
	// is set. Passed through so the policy survives an API re-sync from the
	// orchestrator's sandbox list (mirrors auto_pause); the orchestrator itself
	// does not act on it — the API evictor does.
	AutoPauseFilesystemOnly bool `protobuf:"varint,25,opt,name=auto_pause_filesystem_only,json=autoPauseFilesystemOnly,proto3" json:"auto_pause_filesystem_only,omitempty"`
	// Retention of sandbox events in days
	EventsTtlDays int64 `protobuf:"varint,26,opt,name=events_ttl_days,json=eventsTtlDays,proto3" json:"events_ttl_days,omitempty"`
	// Sandbox workload identity configuration requested at create time. Absent on
	// older serialized configs, which decode as no workload identity.
	Iam           *SandboxIam `protobuf:"bytes,27,opt,name=iam,proto3,oneof" json:"iam,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxConfig) Reset() {
	*x = SandboxConfig{}
	mi := &file_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxConfig) ProtoMessage() {}

func (x *SandboxConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxConfig.ProtoReflect.Descriptor instead.
func (*SandboxConfig) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxConfig) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SandboxConfig) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *SandboxConfig) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *SandboxConfig) GetFirecrackerVersion() string {
	if x != nil {
		return x.FirecrackerVersion
	}
	return ""
}

func (x *SandboxConfig) GetHugePages() bool {
	if x != nil {
		return x.HugePages
	}
	return false
}

func (x *SandboxConfig) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxConfig) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *SandboxConfig) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SandboxConfig) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

func (x *SandboxConfig) GetEnvdVersion() string {
	if x != nil {
		return x.EnvdVersion
	}
	return ""
}

func (x *SandboxConfig) GetVcpu() int64 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *SandboxConfig) GetRamMb() int64 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

func (x *SandboxConfig) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *SandboxConfig) GetMaxSandboxLength() int64 {
	if x != nil {
		return x.MaxSandboxLength
	}
	return 0
}

func (x *SandboxConfig) GetTotalDiskSizeMb() int64 {
	if x != nil {
		return x.TotalDiskSizeMb
	}
	return 0
}

func (x *SandboxConfig) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *SandboxConfig) GetBaseTemplateId() string {
	if x != nil {
		return x.BaseTemplateId
	}
	return ""
}

func (x *SandboxConfig) GetAutoPause() bool {
	if x != nil {
		return x.AutoPause
	}
	return false
}

func (x *SandboxConfig) GetEnvdAccessToken() string {
	if x != nil && x.EnvdAccessToken != nil {
		return *x.EnvdAccessToken
	}
	return ""
}

func (x *SandboxConfig) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SandboxConfig) GetAllowInternetAccess() bool {
	if x != nil && x.AllowInternetAccess != nil {
		return *x.AllowInternetAccess
	}
	return false
}

func (x *SandboxConfig) GetNetwork() *SandboxNetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *SandboxConfig) GetVolumeMounts() []*SandboxVolumeMount {
	if x != nil {
		return x.VolumeMounts
	}
	return nil
}

func (x *SandboxConfig) GetAutoResume() *SandboxAutoResumeConfig {
	if x != nil {
		return x.AutoResume
	}
	return nil
}

func (x *SandboxConfig) GetAutoPauseFilesystemOnly() bool {
	if x != nil {
		return x.AutoPauseFilesystemOnly
	}
	return false
}

func (x *SandboxConfig) GetEventsTtlDays() int64 {
	if x != nil {
		return x.EventsTtlDays
	}
	return 0
}

func (x *SandboxConfig) GetIam() *SandboxIam {
	if x != nil {
		return x.Iam
	}
	return nil
}

// Sandbox workload identity configuration. A non-empty tokens map defines the
// sandbox workload identity, which the orchestrator derives from the existing
// trusted team_id, sandbox_id, execution_id and template_id fields. No
// credential is minted, signed, or delivered here.
type SandboxIam struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Named workload-token definitions, keyed by a caller-chosen token name.
	Tokens        map[string]*SandboxIamToken `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxIam) Reset() {
	*x = SandboxIam{}
	mi := &file_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxIam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxIam) ProtoMessage() {}

func (x *SandboxIam) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxIam.ProtoReflect.Descriptor instead.
func (*SandboxIam) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *SandboxIam) GetTokens() map[string]*SandboxIamToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// A named workload-token definition. file_path is intentionally omitted: only
// absent/null is accepted at admission, so file delivery is not represented.
type SandboxIamToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audience      string                 `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxIamToken) Reset() {
	*x = SandboxIamToken{}
	mi := &file_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxIamToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxIamToken) ProtoMessage() {}

func (x *SandboxIamToken) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxIamToken.ProtoReflect.Descriptor instead.
func (*SandboxIamToken) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *SandboxIamToken) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *SandboxIamToken) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type SandboxAutoResumeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Policy values are owned by the API layer today (e.g. "off", "any").
	Policy string `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	// Timeout requested on initial sandbox create (seconds).
	TimeoutSeconds uint64 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxAutoResumeConfig) Reset() {
	*x = SandboxAutoResumeConfig{}
	mi := &file_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxAutoResumeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxAutoResumeConfig) ProtoMessage() {}

func (x *SandboxAutoResumeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxAutoResumeConfig.ProtoReflect.Descriptor instead.
func (*SandboxAutoResumeConfig) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *SandboxAutoResumeConfig) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *SandboxAutoResumeConfig) GetTimeoutSeconds() uint64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type SandboxVolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxVolumeMount) Reset() {
	*x = SandboxVolumeMount{}
	mi := &file_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxVolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxVolumeMount) ProtoMessage() {}

func (x *SandboxVolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxVolumeMount.ProtoReflect.Descriptor instead.
func (*SandboxVolumeMount) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *SandboxVolumeMount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SandboxVolumeMount) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SandboxVolumeMount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SandboxVolumeMount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SandboxNetworkConfig struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Egress        *SandboxNetworkEgressConfig  `protobuf:"bytes,1,opt,name=egress,proto3,oneof" json:"egress,omitempty"`
	Ingress       *SandboxNetworkIngressConfig `protobuf:"bytes,2,opt,name=ingress,proto3,oneof" json:"ingress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxNetworkConfig) Reset() {
	*x = SandboxNetworkConfig{}
	mi := &file_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxNetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxNetworkConfig) ProtoMessage() {}

func (x *SandboxNetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxNetworkConfig.ProtoReflect.Descriptor instead.
func (*SandboxNetworkConfig) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *SandboxNetworkConfig) GetEgress() *SandboxNetworkEgressConfig {
	if x != nil {
		return x.Egress
	}
	return nil
}

func (x *SandboxNetworkConfig) GetIngress() *SandboxNetworkIngressConfig {
	if x != nil {
		return x.Ingress
	}
	return nil
}

type SandboxNetworkTransform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       map[string]string      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxNetworkTransform) Reset() {
	*x = SandboxNetworkTransform{}
	mi := &file_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxNetworkTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxNetworkTransform) ProtoMessage() {}

func (x *SandboxNetworkTransform) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxNetworkTransform.ProtoReflect.Descriptor instead.
func (*SandboxNetworkTransform) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *SandboxNetworkTransform) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type SandboxNetworkRule struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Transform     *SandboxNetworkTransform `protobuf:"bytes,1,opt,name=transform,proto3,oneof" json:"transform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxNetworkRule) Reset() {
	*x = SandboxNetworkRule{}
	mi := &file_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxNetworkRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxNetworkRule) ProtoMessage() {}

func (x *SandboxNetworkRule) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxNetworkRule.ProtoReflect.Descriptor instead.
func (*SandboxNetworkRule) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *SandboxNetworkRule) GetTransform() *SandboxNetworkTransform {
	if x != nil {
		return x.Transform
	}
	return nil
}

type SandboxNetworkDomainRules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*SandboxNetworkRule  `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxNetworkDomainRules) Reset() {
	*x = SandboxNetworkDomainRules{}
	mi := &file_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxNetworkDomainRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxNetworkDomainRules) ProtoMessage() {}

func (x *SandboxNetworkDomainRules) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxNetworkDomainRules.ProtoReflect.Descriptor instead.
func (*SandboxNetworkDomainRules) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *SandboxNetworkDomainRules) GetRules() []*SandboxNetworkRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type SandboxNetworkEgressConfig struct {
	state          protoimpl.MessageState                `protogen:"open.v1"`
	AllowedCidrs   []string                              `protobuf:"bytes,1,rep,name=allowed_cidrs,json=allowedCidrs,proto3" json:"allowed_cidrs,omitempty"`
	DeniedCidrs    []string                              `protobuf:"bytes,2,rep,name=denied_cidrs,json=deniedCidrs,proto3" json:"denied_cidrs,omitempty"`
	AllowedDomains []string                              `protobuf:"bytes,3,rep,name=allowed_domains,json=allowedDomains,proto3" json:"allowed_domains,omitempty"`
	Rules          map[string]*SandboxNetworkDomainRules `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// BYOP SOCKS5 egress proxy.
	EgressProxyAddress  string `protobuf:"bytes,5,opt,name=egress_proxy_address,json=egressProxyAddress,proto3" json:"egress_proxy_address,omitempty"`
	EgressProxyUsername string `protobuf:"bytes,6,opt,name=egress_proxy_username,json=egressProxyUsername,proto3" json:"egress_proxy_username,omitempty"`
	EgressProxyPassword string `protobuf:"bytes,7,opt,name=egress_proxy_password,json=egressProxyPassword,proto3" json:"egress_proxy_password,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SandboxNetworkEgressConfig) Reset() {
	*x = SandboxNetworkEgressConfig{}
	mi := &file_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxNetworkEgressConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxNetworkEgressConfig) ProtoMessage() {}

func (x *SandboxNetworkEgressConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxNetworkEgressConfig.ProtoReflect.Descriptor instead.
func (*SandboxNetworkEgressConfig) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *SandboxNetworkEgressConfig) GetAllowedCidrs() []string {
	if x != nil {
		return x.AllowedCidrs
	}
	return nil
}

func (x *SandboxNetworkEgressConfig) GetDeniedCidrs() []string {
	if x != nil {
		return x.DeniedCidrs
	}
	return nil
}

func (x *SandboxNetworkEgressConfig) GetAllowedDomains() []string {
	if x != nil {
		return x.AllowedDomains
	}
	return nil
}

func (x *SandboxNetworkEgressConfig) GetRules() map[string]*SandboxNetworkDomainRules {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *SandboxNetworkEgressConfig) GetEgressProxyAddress() string {
	if x != nil {
		return x.EgressProxyAddress
	}
	return ""
}

func (x *SandboxNetworkEgressConfig) GetEgressProxyUsername() string {
	if x != nil {
		return x.EgressProxyUsername
	}
	return ""
}

func (x *SandboxNetworkEgressConfig) GetEgressProxyPassword() string {
	if x != nil {
		return x.EgressProxyPassword
	}
	return ""
}

type SandboxNetworkIngressConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TrafficAccessToken *string                `protobuf:"bytes,1,opt,name=traffic_access_token,json=trafficAccessToken,proto3,oneof" json:"traffic_access_token,omitempty"`
	MaskRequestHost    *string                `protobuf:"bytes,2,opt,name=mask_request_host,json=maskRequestHost,proto3,oneof" json:"mask_request_host,omitempty"`
	HttpsPorts         []uint32               `protobuf:"varint,3,rep,packed,name=https_ports,json=httpsPorts,proto3" json:"https_ports,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SandboxNetworkIngressConfig) Reset() {
	*x = SandboxNetworkIngressConfig{}
	mi := &file_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxNetworkIngressConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxNetworkIngressConfig) ProtoMessage() {}

func (x *SandboxNetworkIngressConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxNetworkIngressConfig.ProtoReflect.Descriptor instead.
func (*SandboxNetworkIngressConfig) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *SandboxNetworkIngressConfig) GetTrafficAccessToken() string {
	if x != nil && x.TrafficAccessToken != nil {
		return *x.TrafficAccessToken
	}
	return ""
}

func (x *SandboxNetworkIngressConfig) GetMaskRequestHost() string {
	if x != nil && x.MaskRequestHost != nil {
		return *x.MaskRequestHost
	}
	return ""
}

func (x *SandboxNetworkIngressConfig) GetHttpsPorts() []uint32 {
	if x != nil {
		return x.HttpsPorts
	}
	return nil
}

type SandboxCreateRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Sandbox   *SandboxConfig         `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	StartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// When true, resume by cold-booting from the snapshot's rootfs even when it
	// includes a memory snapshot. The request can only widen toward the no-memory
	// path — it can never force a memory restore of a snapshot that has none.
	// Absent = the snapshot's own metadata alone selects the boot path, so
	// existing callers are unaffected. Request-scoped: nothing durable records it.
	FilesystemBoot *bool `protobuf:"varint,4,opt,name=filesystem_boot,json=filesystemBoot,proto3,oneof" json:"filesystem_boot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxCreateRequest) Reset() {
	*x = SandboxCreateRequest{}
	mi := &file_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCreateRequest) ProtoMessage() {}

func (x *SandboxCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCreateRequest.ProtoReflect.Descriptor instead.
func (*SandboxCreateRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *SandboxCreateRequest) GetSandbox() *SandboxConfig {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *SandboxCreateRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SandboxCreateRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *SandboxCreateRequest) GetFilesystemBoot() bool {
	if x != nil && x.FilesystemBoot != nil {
		return *x.FilesystemBoot
	}
	return false
}

type SandboxCreateResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClientId           string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SchedulingMetadata *SchedulingMetadata    `protobuf:"bytes,2,opt,name=scheduling_metadata,json=schedulingMetadata,proto3" json:"scheduling_metadata,omitempty"`
	// Echoes whether the sandbox cold-booted from its rootfs (vs a memory
	// restore). Absent from orchestrators that predate filesystem_boot, so a
	// caller that demanded a filesystem boot can detect an unhonored demand
	// instead of trusting deploy ordering.
	FilesystemBootApplied bool `protobuf:"varint,3,opt,name=filesystem_boot_applied,json=filesystemBootApplied,proto3" json:"filesystem_boot_applied,omitempty"`
	// The Firecracker version the sandbox actually RUNS: the request's
	// declared version resolved through the firecracker-versions flag at
	// start, frozen for the sandbox's lifetime. Callers gating features on the
	// FC version must read this rather than re-deriving it — a re-resolution
	// can disagree with the frozen value whenever the flag changes or the
	// evaluation contexts differ. Empty from orchestrators that predate the
	// field.
	ResolvedFirecrackerVersion string `protobuf:"bytes,4,opt,name=resolved_firecracker_version,json=resolvedFirecrackerVersion,proto3" json:"resolved_firecracker_version,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SandboxCreateResponse) Reset() {
	*x = SandboxCreateResponse{}
	mi := &file_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCreateResponse) ProtoMessage() {}

func (x *SandboxCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCreateResponse.ProtoReflect.Descriptor instead.
func (*SandboxCreateResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *SandboxCreateResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SandboxCreateResponse) GetSchedulingMetadata() *SchedulingMetadata {
	if x != nil {
		return x.SchedulingMetadata
	}
	return nil
}

func (x *SandboxCreateResponse) GetFilesystemBootApplied() bool {
	if x != nil {
		return x.FilesystemBootApplied
	}
	return false
}

func (x *SandboxCreateResponse) GetResolvedFirecrackerVersion() string {
	if x != nil {
		return x.ResolvedFirecrackerVersion
	}
	return ""
}

type SandboxUpdateRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SandboxId string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// All fields are optional — only set fields are applied.
	EndTime       *timestamppb.Timestamp      `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	Egress        *SandboxNetworkEgressConfig `protobuf:"bytes,3,opt,name=egress,proto3,oneof" json:"egress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxUpdateRequest) Reset() {
	*x = SandboxUpdateRequest{}
	mi := &file_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxUpdateRequest) ProtoMessage() {}

func (x *SandboxUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxUpdateRequest.ProtoReflect.Descriptor instead.
func (*SandboxUpdateRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *SandboxUpdateRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxUpdateRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *SandboxUpdateRequest) GetEgress() *SandboxNetworkEgressConfig {
	if x != nil {
		return x.Egress
	}
	return nil
}

type SandboxDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	KillReason    *string                `protobuf:"bytes,2,opt,name=kill_reason,json=killReason,proto3,oneof" json:"kill_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxDeleteRequest) Reset() {
	*x = SandboxDeleteRequest{}
	mi := &file_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxDeleteRequest) ProtoMessage() {}

func (x *SandboxDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxDeleteRequest.ProtoReflect.Descriptor instead.
func (*SandboxDeleteRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *SandboxDeleteRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxDeleteRequest) GetKillReason() string {
	if x != nil && x.KillReason != nil {
		return *x.KillReason
	}
	return ""
}

type SandboxPauseRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SandboxId  string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TemplateId string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	BuildId    string                 `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// When true, persist only the filesystem (no memory snapshot); resuming such
	// a snapshot cold-boots (reboots) from the rootfs. Default false = full memory
	// snapshot, so existing callers are unaffected.
	FilesystemOnly bool `protobuf:"varint,4,opt,name=filesystem_only,json=filesystemOnly,proto3" json:"filesystem_only,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxPauseRequest) Reset() {
	*x = SandboxPauseRequest{}
	mi := &file_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxPauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxPauseRequest) ProtoMessage() {}

func (x *SandboxPauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxPauseRequest.ProtoReflect.Descriptor instead.
func (*SandboxPauseRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *SandboxPauseRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxPauseRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SandboxPauseRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *SandboxPauseRequest) GetFilesystemOnly() bool {
	if x != nil {
		return x.FilesystemOnly
	}
	return false
}

type SchedulingMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// memfile_base_build_id / rootfs_base_build_id are each artifact's root layer
	// (shared across the template's sandboxes); they can differ. build_id is the
	// final/current layer. All also appear in the lists below.
	MemfileBaseBuildId string `protobuf:"bytes,1,opt,name=memfile_base_build_id,json=memfileBaseBuildId,proto3" json:"memfile_base_build_id,omitempty"`
	BuildId            string `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// Deduplicated build IDs whose data each artifact references (all ancestor
	// layers plus the build itself). Sorted; order is not significant. When a
	// list exceeds the cap, the lightest layers are dropped first and the count
	// of dropped layers is reported.
	MemfileBuildIds      []string `protobuf:"bytes,3,rep,name=memfile_build_ids,json=memfileBuildIds,proto3" json:"memfile_build_ids,omitempty"`
	RootfsBuildIds       []string `protobuf:"bytes,4,rep,name=rootfs_build_ids,json=rootfsBuildIds,proto3" json:"rootfs_build_ids,omitempty"`
	MemfileDroppedBuilds uint32   `protobuf:"varint,5,opt,name=memfile_dropped_builds,json=memfileDroppedBuilds,proto3" json:"memfile_dropped_builds,omitempty"`
	RootfsDroppedBuilds  uint32   `protobuf:"varint,6,opt,name=rootfs_dropped_builds,json=rootfsDroppedBuilds,proto3" json:"rootfs_dropped_builds,omitempty"`
	// Referenced bytes per build, aligned with the *_build_ids lists. On save the
	// new memfile layer's bytes are a pre-dedup, block-granular upper bound.
	MemfileBuildBytes []uint64 `protobuf:"varint,7,rep,packed,name=memfile_build_bytes,json=memfileBuildBytes,proto3" json:"memfile_build_bytes,omitempty"`
	RootfsBuildBytes  []uint64 `protobuf:"varint,8,rep,packed,name=rootfs_build_bytes,json=rootfsBuildBytes,proto3" json:"rootfs_build_bytes,omitempty"`
	RootfsBaseBuildId string   `protobuf:"bytes,9,opt,name=rootfs_base_build_id,json=rootfsBaseBuildId,proto3" json:"rootfs_base_build_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SchedulingMetadata) Reset() {
	*x = SchedulingMetadata{}
	mi := &file_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulingMetadata) ProtoMessage() {}

func (x *SchedulingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulingMetadata.ProtoReflect.Descriptor instead.
func (*SchedulingMetadata) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *SchedulingMetadata) GetMemfileBaseBuildId() string {
	if x != nil {
		return x.MemfileBaseBuildId
	}
	return ""
}

func (x *SchedulingMetadata) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *SchedulingMetadata) GetMemfileBuildIds() []string {
	if x != nil {
		return x.MemfileBuildIds
	}
	return nil
}

func (x *SchedulingMetadata) GetRootfsBuildIds() []string {
	if x != nil {
		return x.RootfsBuildIds
	}
	return nil
}

func (x *SchedulingMetadata) GetMemfileDroppedBuilds() uint32 {
	if x != nil {
		return x.MemfileDroppedBuilds
	}
	return 0
}

func (x *SchedulingMetadata) GetRootfsDroppedBuilds() uint32 {
	if x != nil {
		return x.RootfsDroppedBuilds
	}
	return 0
}

func (x *SchedulingMetadata) GetMemfileBuildBytes() []uint64 {
	if x != nil {
		return x.MemfileBuildBytes
	}
	return nil
}

func (x *SchedulingMetadata) GetRootfsBuildBytes() []uint64 {
	if x != nil {
		return x.RootfsBuildBytes
	}
	return nil
}

func (x *SchedulingMetadata) GetRootfsBaseBuildId() string {
	if x != nil {
		return x.RootfsBaseBuildId
	}
	return ""
}

type SandboxPauseResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SchedulingMetadata *SchedulingMetadata    `protobuf:"bytes,1,opt,name=scheduling_metadata,json=schedulingMetadata,proto3" json:"scheduling_metadata,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SandboxPauseResponse) Reset() {
	*x = SandboxPauseResponse{}
	mi := &file_orchestrator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxPauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxPauseResponse) ProtoMessage() {}

func (x *SandboxPauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxPauseResponse.ProtoReflect.Descriptor instead.
func (*SandboxPauseResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{17}
}

func (x *SandboxPauseResponse) GetSchedulingMetadata() *SchedulingMetadata {
	if x != nil {
		return x.SchedulingMetadata
	}
	return nil
}

type SandboxCheckpointRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SandboxId string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	BuildId   string                 `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// Provenance stamped onto the snapshot's storage objects for the storage
	// index (e.g. template_id). Opaque to the orchestrator, which just forwards
	// it to object metadata.
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxCheckpointRequest) Reset() {
	*x = SandboxCheckpointRequest{}
	mi := &file_orchestrator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCheckpointRequest) ProtoMessage() {}

func (x *SandboxCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCheckpointRequest.ProtoReflect.Descriptor instead.
func (*SandboxCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{18}
}

func (x *SandboxCheckpointRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxCheckpointRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *SandboxCheckpointRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SandboxCheckpointResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SchedulingMetadata *SchedulingMetadata    `protobuf:"bytes,1,opt,name=scheduling_metadata,json=schedulingMetadata,proto3" json:"scheduling_metadata,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SandboxCheckpointResponse) Reset() {
	*x = SandboxCheckpointResponse{}
	mi := &file_orchestrator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCheckpointResponse) ProtoMessage() {}

func (x *SandboxCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCheckpointResponse.ProtoReflect.Descriptor instead.
func (*SandboxCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{19}
}

func (x *SandboxCheckpointResponse) GetSchedulingMetadata() *SchedulingMetadata {
	if x != nil {
		return x.SchedulingMetadata
	}
	return nil
}

type SandboxCheckpointStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxCheckpointStatusRequest) Reset() {
	*x = SandboxCheckpointStatusRequest{}
	mi := &file_orchestrator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCheckpointStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCheckpointStatusRequest) ProtoMessage() {}

func (x *SandboxCheckpointStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCheckpointStatusRequest.ProtoReflect.Descriptor instead.
func (*SandboxCheckpointStatusRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{20}
}

func (x *SandboxCheckpointStatusRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxCheckpointStatusRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *SandboxCheckpointStatusRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SandboxCheckpointStatusRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type SandboxCheckpointStatusResponse struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Native         bool                    `protobuf:"varint,1,opt,name=native,proto3" json:"native,omitempty"`
	SnapshotState  CheckpointSnapshotState `protobuf:"varint,2,opt,name=snapshot_state,json=snapshotState,proto3,enum=CheckpointSnapshotState" json:"snapshot_state,omitempty"`
	RuntimeState   CheckpointRuntimeState  `protobuf:"varint,3,opt,name=runtime_state,json=runtimeState,proto3,enum=CheckpointRuntimeState" json:"runtime_state,omitempty"`
	BuildId        string                  `protobuf:"bytes,4,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	ExecutionId    string                  `protobuf:"bytes,5,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	LifecycleId    string                  `protobuf:"bytes,6,opt,name=lifecycle_id,json=lifecycleId,proto3" json:"lifecycle_id,omitempty"`
	RuntimeBuildId string                  `protobuf:"bytes,7,opt,name=runtime_build_id,json=runtimeBuildId,proto3" json:"runtime_build_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxCheckpointStatusResponse) Reset() {
	*x = SandboxCheckpointStatusResponse{}
	mi := &file_orchestrator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCheckpointStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCheckpointStatusResponse) ProtoMessage() {}

func (x *SandboxCheckpointStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCheckpointStatusResponse.ProtoReflect.Descriptor instead.
func (*SandboxCheckpointStatusResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{21}
}

func (x *SandboxCheckpointStatusResponse) GetNative() bool {
	if x != nil {
		return x.Native
	}
	return false
}

func (x *SandboxCheckpointStatusResponse) GetSnapshotState() CheckpointSnapshotState {
	if x != nil {
		return x.SnapshotState
	}
	return CheckpointSnapshotState_CHECKPOINT_SNAPSHOT_UNKNOWN
}

func (x *SandboxCheckpointStatusResponse) GetRuntimeState() CheckpointRuntimeState {
	if x != nil {
		return x.RuntimeState
	}
	return CheckpointRuntimeState_CHECKPOINT_RUNTIME_UNKNOWN
}

func (x *SandboxCheckpointStatusResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *SandboxCheckpointStatusResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SandboxCheckpointStatusResponse) GetLifecycleId() string {
	if x != nil {
		return x.LifecycleId
	}
	return ""
}

func (x *SandboxCheckpointStatusResponse) GetRuntimeBuildId() string {
	if x != nil {
		return x.RuntimeBuildId
	}
	return ""
}

type RunningSandbox struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: the API no longer rebuilds sandbox state from this list. Redis
	// is the source of truth; List is only used to detect sandboxes running on a
	// node that the store does not know about, so they can be killed. The fields
	// below carry everything that decision needs. Still populated so API
	// instances predating those fields keep working during a rollout.
	//
	// Deprecated: Marked as deprecated in orchestrator.proto.
	Config    *SandboxConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ClientId  string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Minimal set required to detect an orphaned sandbox and kill it.
	// sandbox_id + team_id form the store key. execution_id is carried in the
	// edge sandbox-catalog delete event, so a cluster node's routing entry is
	// evicted too. vcpu/ram_mb feed the node's optimistic resource accounting.
	SandboxId     string `protobuf:"bytes,5,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TeamId        string `protobuf:"bytes,6,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ExecutionId   string `protobuf:"bytes,7,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Vcpu          int64  `protobuf:"varint,8,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	RamMb         int64  `protobuf:"varint,9,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningSandbox) Reset() {
	*x = RunningSandbox{}
	mi := &file_orchestrator_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningSandbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningSandbox) ProtoMessage() {}

func (x *RunningSandbox) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningSandbox.ProtoReflect.Descriptor instead.
func (*RunningSandbox) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{22}
}

// Deprecated: Marked as deprecated in orchestrator.proto.
func (x *RunningSandbox) GetConfig() *SandboxConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RunningSandbox) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RunningSandbox) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *RunningSandbox) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *RunningSandbox) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RunningSandbox) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *RunningSandbox) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *RunningSandbox) GetVcpu() int64 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *RunningSandbox) GetRamMb() int64 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

type SandboxListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*RunningSandbox      `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxListResponse) Reset() {
	*x = SandboxListResponse{}
	mi := &file_orchestrator_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxListResponse) ProtoMessage() {}

func (x *SandboxListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxListResponse.ProtoReflect.Descriptor instead.
func (*SandboxListResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_proto_rawDescGZIP(), []int{23}
}

func (x *SandboxListResponse) GetSandboxes() []*RunningSandbox {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

var File_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x12orchestrator.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\n" +
	"\n" +
	"\rSandboxConfig\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12/\n" +
	"\x13firecracker_version\x18\x04 \x01(\tR\x12firecrackerVersion\x12\x1d\n" +
	"\n" +
	"huge_pages\x18\x05 \x01(\bR\thugePages\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x06 \x01(\tR\tsandboxId\x126\n" +
	"\benv_vars\x18\a \x03(\v2\x1b.SandboxConfig.EnvVarsEntryR\aenvVars\x128\n" +
	"\bmetadata\x18\b \x03(\v2\x1c.SandboxConfig.MetadataEntryR\bmetadata\x12\x19\n" +
	"\x05alias\x18\t \x01(\tH\x00R\x05alias\x88\x01\x01\x12!\n" +
	"\fenvd_version\x18\n" +
	" \x01(\tR\venvdVersion\x12\x12\n" +
	"\x04vcpu\x18\v \x01(\x03R\x04vcpu\x12\x15\n" +
	"\x06ram_mb\x18\f \x01(\x03R\x05ramMb\x12\x17\n" +
	"\ateam_id\x18\r \x01(\tR\x06teamId\x12,\n" +
	"\x12max_sandbox_length\x18\x0e \x01(\x03R\x10maxSandboxLength\x12+\n" +
	"\x12total_disk_size_mb\x18\x0f \x01(\x03R\x0ftotalDiskSizeMb\x12\x1a\n" +
	"\bsnapshot\x18\x10 \x01(\bR\bsnapshot\x12(\n" +
	"\x10base_template_id\x18\x11 \x01(\tR\x0ebaseTemplateId\x12\x1d\n" +
	"\n" +
	"auto_pause\x18\x12 \x01(\bR\tautoPause\x12/\n" +
	"\x11envd_access_token\x18\x13 \x01(\tH\x01R\x0fenvdAccessToken\x88\x01\x01\x12!\n" +
	"\fexecution_id\x18\x14 \x01(\tR\vexecutionId\x127\n" +
	"\x15allow_internet_access\x18\x15 \x01(\bH\x02R\x13allowInternetAccess\x88\x01\x01\x124\n" +
	"\anetwork\x18\x16 \x01(\v2\x15.SandboxNetworkConfigH\x03R\anetwork\x88\x01\x01\x127\n" +
	"\fvolumeMounts\x18\x17 \x03(\v2\x13.SandboxVolumeMountR\fvolumeMounts\x12>\n" +
	"\vauto_resume\x18\x18 \x01(\v2\x18.SandboxAutoResumeConfigH\x04R\n" +
	"autoResume\x88\x01\x01\x12;\n" +
	"\x1aauto_pause_filesystem_only\x18\x19 \x01(\bR\x17autoPauseFilesystemOnly\x12&\n" +
	"\x0fevents_ttl_days\x18\x1a \x01(\x03R\reventsTtlDays\x12\"\n" +
	"\x03iam\x18\x1b \x01(\v2\v.SandboxIamH\x05R\x03iam\x88\x01\x01\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_aliasB\x14\n" +
	"\x12_envd_access_tokenB\x18\n" +
	"\x16_allow_internet_accessB\n" +
	"\n" +
	"\b_networkB\x0e\n" +
	"\f_auto_resumeB\x06\n" +
	"\x04_iam\"\x8a\x01\n" +
	"\n" +
	"SandboxIam\x12/\n" +
	"\x06tokens\x18\x01 \x03(\v2\x17.SandboxIam.TokensEntryR\x06tokens\x1aK\n" +
	"\vTokensEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.SandboxIamTokenR\x05value:\x028\x01\"L\n" +
	"\x0fSandboxIamToken\x12\x1a\n" +
	"\baudience\x18\x01 \x01(\tR\baudience\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\"Z\n" +
	"\x17SandboxAutoResumeConfig\x12\x16\n" +
	"\x06policy\x18\x01 \x01(\tR\x06policy\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x04R\x0etimeoutSeconds\"`\n" +
	"\x12SandboxVolumeMount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\xa4\x01\n" +
	"\x14SandboxNetworkConfig\x128\n" +
	"\x06egress\x18\x01 \x01(\v2\x1b.SandboxNetworkEgressConfigH\x00R\x06egress\x88\x01\x01\x12;\n" +
	"\aingress\x18\x02 \x01(\v2\x1c.SandboxNetworkIngressConfigH\x01R\aingress\x88\x01\x01B\t\n" +
	"\a_egressB\n" +
	"\n" +
	"\b_ingress\"\x96\x01\n" +
	"\x17SandboxNetworkTransform\x12?\n" +
	"\aheaders\x18\x01 \x03(\v2%.SandboxNetworkTransform.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x12SandboxNetworkRule\x12;\n" +
	"\ttransform\x18\x01 \x01(\v2\x18.SandboxNetworkTransformH\x00R\ttransform\x88\x01\x01B\f\n" +
	"\n" +
	"_transform\"F\n" +
	"\x19SandboxNetworkDomainRules\x12)\n" +
	"\x05rules\x18\x01 \x03(\v2\x13.SandboxNetworkRuleR\x05rules\"\xbb\x03\n" +
	"\x1aSandboxNetworkEgressConfig\x12#\n" +
	"\rallowed_cidrs\x18\x01 \x03(\tR\fallowedCidrs\x12!\n" +
	"\fdenied_cidrs\x18\x02 \x03(\tR\vdeniedCidrs\x12'\n" +
	"\x0fallowed_domains\x18\x03 \x03(\tR\x0eallowedDomains\x12<\n" +
	"\x05rules\x18\x04 \x03(\v2&.SandboxNetworkEgressConfig.RulesEntryR\x05rules\x120\n" +
	"\x14egress_proxy_address\x18\x05 \x01(\tR\x12egressProxyAddress\x122\n" +
	"\x15egress_proxy_username\x18\x06 \x01(\tR\x13egressProxyUsername\x122\n" +
	"\x15egress_proxy_password\x18\a \x01(\tR\x13egressProxyPassword\x1aT\n" +
	"\n" +
	"RulesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.SandboxNetworkDomainRulesR\x05value:\x028\x01\"\xd5\x01\n" +
	"\x1bSandboxNetworkIngressConfig\x125\n" +
	"\x14traffic_access_token\x18\x01 \x01(\tH\x00R\x12trafficAccessToken\x88\x01\x01\x12/\n" +
	"\x11mask_request_host\x18\x02 \x01(\tH\x01R\x0fmaskRequestHost\x88\x01\x01\x12\x1f\n" +
	"\vhttps_ports\x18\x03 \x03(\rR\n" +
	"httpsPortsB\x17\n" +
	"\x15_traffic_access_tokenB\x14\n" +
	"\x12_mask_request_host\"\xf4\x01\n" +
	"\x14SandboxCreateRequest\x12(\n" +
	"\asandbox\x18\x01 \x01(\v2\x0e.SandboxConfigR\asandbox\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12,\n" +
	"\x0ffilesystem_boot\x18\x04 \x01(\bH\x00R\x0efilesystemBoot\x88\x01\x01B\x12\n" +
	"\x10_filesystem_boot\"\xf4\x01\n" +
	"\x15SandboxCreateResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12D\n" +
	"\x13scheduling_metadata\x18\x02 \x01(\v2\x13.SchedulingMetadataR\x12schedulingMetadata\x126\n" +
	"\x17filesystem_boot_applied\x18\x03 \x01(\bR\x15filesystemBootApplied\x12@\n" +
	"\x1cresolved_firecracker_version\x18\x04 \x01(\tR\x1aresolvedFirecrackerVersion\"\xc3\x01\n" +
	"\x14SandboxUpdateRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12:\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\aendTime\x88\x01\x01\x128\n" +
	"\x06egress\x18\x03 \x01(\v2\x1b.SandboxNetworkEgressConfigH\x01R\x06egress\x88\x01\x01B\v\n" +
	"\t_end_timeB\t\n" +
	"\a_egress\"k\n" +
	"\x14SandboxDeleteRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12$\n" +
	"\vkill_reason\x18\x02 \x01(\tH\x00R\n" +
	"killReason\x88\x01\x01B\x0e\n" +
	"\f_kill_reason\"\x99\x01\n" +
	"\x13SandboxPauseRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x19\n" +
	"\bbuild_id\x18\x03 \x01(\tR\abuildId\x12'\n" +
	"\x0ffilesystem_only\x18\x04 \x01(\bR\x0efilesystemOnly\"\xb1\x03\n" +
	"\x12SchedulingMetadata\x121\n" +
	"\x15memfile_base_build_id\x18\x01 \x01(\tR\x12memfileBaseBuildId\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\x12*\n" +
	"\x11memfile_build_ids\x18\x03 \x03(\tR\x0fmemfileBuildIds\x12(\n" +
	"\x10rootfs_build_ids\x18\x04 \x03(\tR\x0erootfsBuildIds\x124\n" +
	"\x16memfile_dropped_builds\x18\x05 \x01(\rR\x14memfileDroppedBuilds\x122\n" +
	"\x15rootfs_dropped_builds\x18\x06 \x01(\rR\x13rootfsDroppedBuilds\x12.\n" +
	"\x13memfile_build_bytes\x18\a \x03(\x04R\x11memfileBuildBytes\x12,\n" +
	"\x12rootfs_build_bytes\x18\b \x03(\x04R\x10rootfsBuildBytes\x12/\n" +
	"\x14rootfs_base_build_id\x18\t \x01(\tR\x11rootfsBaseBuildId\"\\\n" +
	"\x14SandboxPauseResponse\x12D\n" +
	"\x13scheduling_metadata\x18\x01 \x01(\v2\x13.SchedulingMetadataR\x12schedulingMetadata\"\xd6\x01\n" +
	"\x18SandboxCheckpointRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x19\n" +
	"\bbuild_id\x18\x03 \x01(\tR\abuildId\x12C\n" +
	"\bmetadata\x18\x04 \x03(\v2'.SandboxCheckpointRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x19SandboxCheckpointResponse\x12D\n" +
	"\x13scheduling_metadata\x18\x01 \x01(\v2\x13.SchedulingMetadataR\x12schedulingMetadata\"\x96\x01\n" +
	"\x1eSandboxCheckpointStatusRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\x12\x17\n" +
	"\ateam_id\x18\x04 \x01(\tR\x06teamId\"\xc3\x02\n" +
	"\x1fSandboxCheckpointStatusResponse\x12\x16\n" +
	"\x06native\x18\x01 \x01(\bR\x06native\x12?\n" +
	"\x0esnapshot_state\x18\x02 \x01(\x0e2\x18.CheckpointSnapshotStateR\rsnapshotState\x12<\n" +
	"\rruntime_state\x18\x03 \x01(\x0e2\x17.CheckpointRuntimeStateR\fruntimeState\x12\x19\n" +
	"\bbuild_id\x18\x04 \x01(\tR\abuildId\x12!\n" +
	"\fexecution_id\x18\x05 \x01(\tR\vexecutionId\x12!\n" +
	"\flifecycle_id\x18\x06 \x01(\tR\vlifecycleId\x12(\n" +
	"\x10runtime_build_id\x18\a \x01(\tR\x0eruntimeBuildId\"\xd1\x02\n" +
	"\x0eRunningSandbox\x12*\n" +
	"\x06config\x18\x01 \x01(\v2\x0e.SandboxConfigB\x02\x18\x01R\x06config\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x05 \x01(\tR\tsandboxId\x12\x17\n" +
	"\ateam_id\x18\x06 \x01(\tR\x06teamId\x12!\n" +
	"\fexecution_id\x18\a \x01(\tR\vexecutionId\x12\x12\n" +
	"\x04vcpu\x18\b \x01(\x03R\x04vcpu\x12\x15\n" +
	"\x06ram_mb\x18\t \x01(\x03R\x05ramMb\"D\n" +
	"\x13SandboxListResponse\x12-\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x0f.RunningSandboxR\tsandboxes*\xf7\x01\n" +
	"\x17CheckpointSnapshotState\x12\x1f\n" +
	"\x1bCHECKPOINT_SNAPSHOT_UNKNOWN\x10\x00\x12#\n" +
	"\x1fCHECKPOINT_SNAPSHOT_IN_PROGRESS\x10\x01\x12!\n" +
	"\x1dCHECKPOINT_SNAPSHOT_COMMITTED\x10\x02\x12%\n" +
	"!CHECKPOINT_SNAPSHOT_NOT_COMMITTED\x10\x03\x12*\n" +
	"&CHECKPOINT_SNAPSHOT_DURABILITY_UNKNOWN\x10\x04\x12 \n" +
	"\x1cCHECKPOINT_SNAPSHOT_CAPTURED\x10\x05*\x9e\x01\n" +
	"\x16CheckpointRuntimeState\x12\x1e\n" +
	"\x1aCHECKPOINT_RUNTIME_UNKNOWN\x10\x00\x12$\n" +
	" CHECKPOINT_RUNTIME_TRANSITIONING\x10\x01\x12\x1e\n" +
	"\x1aCHECKPOINT_RUNTIME_RUNNING\x10\x02\x12\x1e\n" +
	"\x1aCHECKPOINT_RUNTIME_STOPPED\x10\x032\xc3\x03\n" +
	"\x0eSandboxService\x127\n" +
	"\x06Create\x12\x15.SandboxCreateRequest\x1a\x16.SandboxCreateResponse\x127\n" +
	"\x06Update\x12\x15.SandboxUpdateRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x14.SandboxListResponse\x127\n" +
	"\x06Delete\x12\x15.SandboxDeleteRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\x05Pause\x12\x14.SandboxPauseRequest\x1a\x15.SandboxPauseResponse\x12C\n" +
	"\n" +
	"Checkpoint\x12\x19.SandboxCheckpointRequest\x1a\x1a.SandboxCheckpointResponse\x12U\n" +
	"\x10CheckpointStatus\x12\x1f.SandboxCheckpointStatusRequest\x1a .SandboxCheckpointStatusResponseB/Z-https://github.com/e2b-dev/infra/orchestratorb\x06proto3"

var (
	file_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_proto_rawDescData
}

var file_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_orchestrator_proto_goTypes = []any{
	(CheckpointSnapshotState)(0),            // 0: CheckpointSnapshotState
	(CheckpointRuntimeState)(0),             // 1: CheckpointRuntimeState
	(*SandboxConfig)(nil),                   // 2: SandboxConfig
	(*SandboxIam)(nil),                      // 3: SandboxIam
	(*SandboxIamToken)(nil),                 // 4: SandboxIamToken
	(*SandboxAutoResumeConfig)(nil),         // 5: SandboxAutoResumeConfig
	(*SandboxVolumeMount)(nil),              // 6: SandboxVolumeMount
	(*SandboxNetworkConfig)(nil),            // 7: SandboxNetworkConfig
	(*SandboxNetworkTransform)(nil),         // 8: SandboxNetworkTransform
	(*SandboxNetworkRule)(nil),              // 9: SandboxNetworkRule
	(*SandboxNetworkDomainRules)(nil),       // 10: SandboxNetworkDomainRules
	(*SandboxNetworkEgressConfig)(nil),      // 11: SandboxNetworkEgressConfig
	(*SandboxNetworkIngressConfig)(nil),     // 12: SandboxNetworkIngressConfig
	(*SandboxCreateRequest)(nil),            // 13: SandboxCreateRequest
	(*SandboxCreateResponse)(nil),           // 14: SandboxCreateResponse
	(*SandboxUpdateRequest)(nil),            // 15: SandboxUpdateRequest
	(*SandboxDeleteRequest)(nil),            // 16: SandboxDeleteRequest
	(*SandboxPauseRequest)(nil),             // 17: SandboxPauseRequest
	(*SchedulingMetadata)(nil),              // 18: SchedulingMetadata
	(*SandboxPauseResponse)(nil),            // 19: SandboxPauseResponse
	(*SandboxCheckpointRequest)(nil),        // 20: SandboxCheckpointRequest
	(*SandboxCheckpointResponse)(nil),       // 21: SandboxCheckpointResponse
	(*SandboxCheckpointStatusRequest)(nil),  // 22: SandboxCheckpointStatusRequest
	(*SandboxCheckpointStatusResponse)(nil), // 23: SandboxCheckpointStatusResponse
	(*RunningSandbox)(nil),                  // 24: RunningSandbox
	(*SandboxListResponse)(nil),             // 25: SandboxListResponse
	nil,                                     // 26: SandboxConfig.EnvVarsEntry
	nil,                                     // 27: SandboxConfig.MetadataEntry
	nil,                                     // 28: SandboxIam.TokensEntry
	nil,                                     // 29: SandboxNetworkTransform.HeadersEntry
	nil,                                     // 30: SandboxNetworkEgressConfig.RulesEntry
	nil,                                     // 31: SandboxCheckpointRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),           // 32: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 33: google.protobuf.Empty
}
var file_orchestrator_proto_depIdxs = []int32{
	26, // 0: SandboxConfig.env_vars:type_name -> SandboxConfig.EnvVarsEntry
	27, // 1: SandboxConfig.metadata:type_name -> SandboxConfig.MetadataEntry
	7,  // 2: SandboxConfig.network:type_name -> SandboxNetworkConfig
	6,  // 3: SandboxConfig.volumeMounts:type_name -> SandboxVolumeMount
	5,  // 4: SandboxConfig.auto_resume:type_name -> SandboxAutoResumeConfig
	3,  // 5: SandboxConfig.iam:type_name -> SandboxIam
	28, // 6: SandboxIam.tokens:type_name -> SandboxIam.TokensEntry
	11, // 7: SandboxNetworkConfig.egress:type_name -> SandboxNetworkEgressConfig
	12, // 8: SandboxNetworkConfig.ingress:type_name -> SandboxNetworkIngressConfig
	29, // 9: SandboxNetworkTransform.headers:type_name -> SandboxNetworkTransform.HeadersEntry
	8,  // 10: SandboxNetworkRule.transform:type_name -> SandboxNetworkTransform
	9,  // 11: SandboxNetworkDomainRules.rules:type_name -> SandboxNetworkRule
	30, // 12: SandboxNetworkEgressConfig.rules:type_name -> SandboxNetworkEgressConfig.RulesEntry
	2,  // 13: SandboxCreateRequest.sandbox:type_name -> SandboxConfig
	32, // 14: SandboxCreateRequest.start_time:type_name -> google.protobuf.Timestamp
	32, // 15: SandboxCreateRequest.end_time:type_name -> google.protobuf.Timestamp
	18, // 16: SandboxCreateResponse.scheduling_metadata:type_name -> SchedulingMetadata
	32, // 17: SandboxUpdateRequest.end_time:type_name -> google.protobuf.Timestamp
	11, // 18: SandboxUpdateRequest.egress:type_name -> SandboxNetworkEgressConfig
	18, // 19: SandboxPauseResponse.scheduling_metadata:type_name -> SchedulingMetadata
	31, // 20: SandboxCheckpointRequest.metadata:type_name -> SandboxCheckpointRequest.MetadataEntry
	18, // 21: SandboxCheckpointResponse.scheduling_metadata:type_name -> SchedulingMetadata
	0,  // 22: SandboxCheckpointStatusResponse.snapshot_state:type_name -> CheckpointSnapshotState
	1,  // 23: SandboxCheckpointStatusResponse.runtime_state:type_name -> CheckpointRuntimeState
	2,  // 24: RunningSandbox.config:type_name -> SandboxConfig
	32, // 25: RunningSandbox.start_time:type_name -> google.protobuf.Timestamp
	32, // 26: RunningSandbox.end_time:type_name -> google.protobuf.Timestamp
	24, // 27: SandboxListResponse.sandboxes:type_name -> RunningSandbox
	4,  // 28: SandboxIam.TokensEntry.value:type_name -> SandboxIamToken
	10, // 29: SandboxNetworkEgressConfig.RulesEntry.value:type_name -> SandboxNetworkDomainRules
	13, // 30: SandboxService.Create:input_type -> SandboxCreateRequest
	15, // 31: SandboxService.Update:input_type -> SandboxUpdateRequest
	33, // 32: SandboxService.List:input_type -> google.protobuf.Empty
	16, // 33: SandboxService.Delete:input_type -> SandboxDeleteRequest
	17, // 34: SandboxService.Pause:input_type -> SandboxPauseRequest
	20, // 35: SandboxService.Checkpoint:input_type -> SandboxCheckpointRequest
	22, // 36: SandboxService.CheckpointStatus:input_type -> SandboxCheckpointStatusRequest
	14, // 37: SandboxService.Create:output_type -> SandboxCreateResponse
	33, // 38: SandboxService.Update:output_type -> google.protobuf.Empty
	25, // 39: SandboxService.List:output_type -> SandboxListResponse
	33, // 40: SandboxService.Delete:output_type -> google.protobuf.Empty
	19, // 41: SandboxService.Pause:output_type -> SandboxPauseResponse
	21, // 42: SandboxService.Checkpoint:output_type -> SandboxCheckpointResponse
	23, // 43: SandboxService.CheckpointStatus:output_type -> SandboxCheckpointStatusResponse
	37, // [37:44] is the sub-list for method output_type
	30, // [30:37] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_orchestrator_proto_init() }
func file_orchestrator_proto_init() {
	if File_orchestrator_proto != nil {
		return
	}
	file_orchestrator_proto_msgTypes[0].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[5].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[7].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[10].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[11].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[13].OneofWrappers = []any{}
	file_orchestrator_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_proto_rawDesc), len(file_orchestrator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_proto_depIdxs,
		EnumInfos:         file_orchestrator_proto_enumTypes,
		MessageInfos:      file_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_proto = out.File
	file_orchestrator_proto_goTypes = nil
	file_orchestrator_proto_depIdxs = nil
}
